### ISSUE TITLE
Feedback 1

### ISSUE THREAD

**Issue by drvpereira** [RodrigoBC2/rock-paper-scissors#1]
- Interessante você ter usado dicionários. Não era minha ideia para a versão inicial, eu ia sugerir para versões posteriores. 
- Perceba que o if user == 2 e o if user == 3 são sempre verificados, mesmo que user seja igual a 1. Sugiro usar elif em vez de if nesses casos. A diferença de performance é insignificante nesse caso, mas imagine que você cria um site pra jogar pedra-papel-tesoura e o site passa a ter milhões de requisições de pessoas jogando. Nesse caso, isso passa a fazer alguma diferença. 
- Perceba também que você tem três trechos de código muito parecidos aqui:

    print('User choose: ROCK.')
    print('Computer choose: ', pc)

    if pc == opt_dict.get(2):
        print('Computer has won!')
    elif pc == opt_dict.get(3):
        print('User has won!')

   Você conseguiria imaginar como criar uma função com esse código e chamar as funções em vez de duplicar esse código?

**Comment by RodrigoBC2** [comment]
1 - Obrigado =)
2 - O elif foi implementado como recomendado, independentemente de ser significante agora ou não;
3 - Foi criado uma função que processa as condições baseadas nos inputs do usuário e do computador e retorna o resultado final
