### ISSUE TITLE
Otimizar ifs usando o opt_dict

### ISSUE THREAD

**Issue by drvpereira** [RodrigoBC2/rock-paper-scissors#10]
Como usar o

`    opt_dict = {1: 'ROCK', 2: 'PAPER', 3: 'SCISSORS'}`

Para otimizar isso aqui?

```
    if user == 1:
        options_counter['user_counter']['rock'].append(1)
    elif user == 2:
        options_counter['user_counter']['paper'].append(1)
    else:
        options_counter['user_counter']['scissors'].append(1)

    if rand == 1:
        options_counter['computer_counter']['rock'].append(1)
    elif rand == 2:
        options_counter['computer_counter']['paper'].append(1)
    else:
        options_counter['computer_counter']['scissors'].append(1)
```

Essas linhas podem, no fim das contas, serem substituidas por algo parecido com isso aqui:

```
options_counter['user_counter'][user] += 1
options_counter['computer_counter'][rand] += 1
```

**Comment by RodrigoBC2** [comment]
No final das contas eu implementei o mesmo _modus operandi_ das outras funções, antes de ver essa issue. Nesse caso que você sugeriu no final, como ele separa a contagem de cada tipo de opção? não ficou claro para mim.

**Comment by drvpereira** [comment]
As chaves dos dictionaries não precisam ser uma constante... você pode usar variáveis:

Por exemplo, se você tiver uma variável que armazene a opção escolhida:
`selected_option = 'rock'`

Então você pode usar o fato de que isso aqui é verdade ao seu favor:
options_counter['user_counter']['rock'] == options_counter['user_counter'][selected_option]

Entendeu?

**Comment by RodrigoBC2** [comment]
Entendi sim. Vou deixar essa issue aberta por enquanto, porque ainda estou pensando nessa solução.
