### ISSUE TITLE
Generalizar regras

### ISSUE THREAD

**Issue by drvpereira** [RodrigoBC2/rock-paper-scissors#11]
Dê uma olhada nessa função que você criou para analisar quem é o ganhador do jogo:

```
def check_bet(user, rand):
    if user == rand:
        return 'A Draw!'
    elif user == 1 and rand != 2 or user == 2 and rand != 3 or user == 3 and rand != 1:
        return 'User has won!'
    else:
        return 'Computer has won!'
```

Essa função funciona muito bem para essas regras do pedra-papel-tesoura. Mas existem outras regras para esse jogo, como o rock-paper-scissors-lizard-spock, que foi citado em um episódio de The Big Bang Theory.

[https://bigbangtheory.fandom.com/wiki/Rock,_Paper,_Scissors,_Lizard,_Spock](https://bigbangtheory.fandom.com/wiki/Rock,_Paper,_Scissors,_Lizard,_Spock)

Como você faria se quisesse mudar as regras do jogo? 

Perceba que se você for colocar todas as regras em um if, o número de possibilidades a serem testadas cresce quadraticamente, da ordem de n*(n-1)/2, onde n é o número de itens que você pode jogar. Com 3 itens (jogo padrão), temos 3 * 2/2 = 3 possibilidades + o empate. Com 5 itens, temos 5*4/2 = 10 possibilidades + o empate. Se inventarmos um jogo com 10 itens, teremos 45 possibilidades + o empate. Então usar if não é a melhor solução aqui porque o if vai ficando cada vez mais complexo, mais ilegível, mais difícil de testar e mais propenso a bugs. Leia [https://pt.wikipedia.org/wiki/Complexidade_ciclom%C3%A1tica](https://pt.wikipedia.org/wiki/Complexidade_ciclom%C3%A1tica)

Então aqui vão dois exercícios pra pensar: 

1. Como usar dicionários (ou lambdas, ou qualquer outra ferramenta que você imagine) para tornar a verificação do ganhador mais simples e flexível? 
2. Como tornar o jogo mais flexível, deixando o jogador escolher no início do jogo com quais regras ele quer jogar?

**Comment by RodrigoBC2** [comment]
1- Eu pensei em fazer algo mais ou menos assim:

`
# dicionario que tem como valores as possibilidades de inputs dos jogadores e as chaves sao listas que possuem as opções que perdem para o oponente.

options = { 0: scissors = ['PAPER', 'LIZARD'],
		     1: paper = ['ROCK', 'SPOCK'],
		     2: rock = ['SCISSORS', 'LIZARD'],
		     3: lizard = ['PAPER', 'SPOCK'],
		     4: spock = ['SCISSORS', 'ROCK'] }

# função para verificar os ganhadores
def check_options(opt_dict.get(user), opt_dict.get(rand)):

        #primeiro laço: veirificar se houve empate, baseado nas strings de entrada
	if opt_dict.get(user) == opt_dict.get(rand):
		return 'A draw!'
        
        # segundo laço: verificar se existe a string do computador está dentro da lista que o usuario tem salvo
	elif opt_dict.get(rand) in options.get(user):
		return 'user won!'

	else
		return 'computer won!'
`
2 - Penso que para solucionar esse requisito, seria um "if" simples do tipo de regra que quer seguir, o código seleciona a função check_bet ou check_options para fazer as verificações de acordo com as regras selecionadas.

**Comment by RodrigoBC2** [comment]
1- Eu pensei em fazer algo mais ou menos assim:

` > dicionario que tem como valores as possibilidades de inputs dos jogadores e as chaves sao listas que possuem as opções que perdem para o oponente.

options = { 0: scissors = ['PAPER', 'LIZARD'],
1: paper = ['ROCK', 'SPOCK'],
2: rock = ['SCISSORS', 'LIZARD'],
3: lizard = ['PAPER', 'SPOCK'],
4: spock = ['SCISSORS', 'ROCK'] }

função para verificar os ganhadores
def check_options(opt_dict.get(user), opt_dict.get(rand)):

> primeiro laço: veirificar se houve empate, baseado nas strings de entrada
if opt_dict.get(user) == opt_dict.get(rand):
	return 'A draw!'
  

> segundo laço: verificar se existe a string do computador está dentro da lista que o usuario tem salvo

elif opt_dict.get(rand) in options.get(user):
	return 'user won!'

else
	return 'computer won!'`
2 - Penso que para solucionar esse requisito, seria um "if" simples do tipo de regra que quer seguir, o código seleciona a função check_bet ou check_options para fazer as verificações de acordo com as regras selecionadas.

**Comment by RodrigoBC2** [comment]
1. Eu pensei em fazer algo mais ou menos assim:

     1.1 Dicionário que armazena uma lista que tem por nome a opção selecionada e as posições são strings das opções que são derrotadas pela opção selecionada.
     1.2 Para verificar quem ganhou, criei uma função que tem como entrada as strings que ambos os competidores selecionaram e em seguida, 3 possíveis verificações: empate, se o usuário ganha ou se o computador ganha. 
     1.3 Para evitar multiplas opções como na função check_bet, o elif faz uma simpels verificação se a string de input do computador está dentro da lista selecionada pelo usuário como "perdedora" da opção que ele escolheu. Se sim, usuário vence, se nao, computador vence.

` 
options = { 0: scissors = ['PAPER', 'LIZARD'],
                   1: paper = ['ROCK', 'SPOCK'],
                   2: rock = ['SCISSORS', 'LIZARD'],
                   3: lizard = ['PAPER', 'SPOCK'],
                   4: spock = ['SCISSORS', 'ROCK'] }


def check_options(opt_dict.get(user), opt_dict.get(rand)):

     if opt_dict.get(user) == opt_dict.get(rand):
          return 'A draw!'

     elif opt_dict.get(rand) in options.get(user):
          return 'user won!'

     else
          return 'computer won!'`

2 - Penso que para solucionar esse requisito, seria um "if" simples do tipo de regra que quer seguir, o código seleciona a função check_bet ou check_options para fazer as verificações de acordo com as regras selecionadas.

**Comment by RodrigoBC2** [comment]
1. Eu pensei em fazer algo mais ou menos assim:

- Dicionário que armazena uma lista que tem por nome a opção selecionada e as posições são strings das opções que são derrotadas pela opção selecionada.

- Para verificar quem ganhou, criei uma função que tem como entrada as strings que ambos os competidores selecionaram e em seguida, 3 possíveis verificações: empate, se o usuário ganha ou se o computador ganha.

- Para evitar multiplas opções como na função check_bet, o elif faz uma simpels verificação se a string de input do computador está dentro da lista selecionada pelo usuário como "perdedora" da opção que ele escolheu. Se sim, usuário vence, se nao, computador vence.

```
options = { 0: scissors = ['PAPER', 'LIZARD'],
                   1: paper = ['ROCK', 'SPOCK'],
                   2: rock = ['SCISSORS', 'LIZARD'],
                   3: lizard = ['PAPER', 'SPOCK'],
                   4: spock = ['SCISSORS', 'ROCK'] }

def check_options(opt_dict.get(user), opt_dict.get(rand)):

     if opt_dict.get(user) == opt_dict.get(rand):
          return 'A draw!'

     elif opt_dict.get(rand) in options.get(user):
         return 'user won!'

     else
         return 'computer won!'
```

2. Penso que para solucionar esse requisito, seria um "if" simples do tipo de regra que quer seguir, o código seleciona a função check_bet ou check_options para fazer as verificações de acordo com as regras selecionadas.

**Comment by RodrigoBC2** [comment]
1. Eu pensei em fazer algo mais ou menos assim:

- Dicionário que armazena uma lista que tem por nome a opção selecionada e as posições são strings das opções que são derrotadas pela opção selecionada.

- Para verificar quem ganhou, criei uma função que tem como entrada as strings que ambos os competidores selecionaram e em seguida, 3 possíveis verificações: empate, se o usuário ganha ou se o computador ganha.

- Para evitar multiplas opções como na função check_bet, o elif faz uma simpels verificação se a string de input do computador está dentro da lista selecionada pelo usuário como "perdedora" da opção que ele escolheu. Se sim, usuário vence, se nao, computador vence.

```
options = { 0: scissors = ['PAPER', 'LIZARD'],
     1: paper = ['ROCK', 'SPOCK'],
     2: rock = ['SCISSORS', 'LIZARD'],
     3: lizard = ['PAPER', 'SPOCK'],
     4: spock = ['SCISSORS', 'ROCK'] }

def check_options(opt_dict.get(user), opt_dict.get(rand)):

     if opt_dict.get(user) == opt_dict.get(rand):
          return 'A draw!'

     elif opt_dict.get(rand) in options.get(user):
         return 'user won!'

     else
         return 'computer won!'
```

2. Penso que para solucionar esse requisito, seria um "if" simples do tipo de regra que quer seguir, o código seleciona a função check_bet ou check_options para fazer as verificações de acordo com as regras selecionadas.

**Comment by RodrigoBC2** [comment]
1. Eu pensei em fazer algo mais ou menos assim:

- Dicionário que armazena uma lista que tem por nome a opção selecionada e as posições são strings das opções que são derrotadas pela opção selecionada.

- Para verificar quem ganhou, criei uma função que tem como entrada as strings que ambos os competidores selecionaram e em seguida, 3 possíveis verificações: empate, se o usuário ganha ou se o computador ganha.

- Para evitar multiplas opções como na função check_bet, o elif faz uma simpels verificação se a string de input do computador está dentro da lista selecionada pelo usuário como "perdedora" da opção que ele escolheu. Se sim, usuário vence, se nao, computador vence.

```
options = { 0: scissors = ['PAPER', 'LIZARD'],
          1: paper = ['ROCK', 'SPOCK'],
          2: rock = ['SCISSORS', 'LIZARD'],
          3: lizard = ['PAPER', 'SPOCK'],
          4: spock = ['SCISSORS', 'ROCK'] }

def check_options(opt_dict.get(user), opt_dict.get(rand)):

     if opt_dict.get(user) == opt_dict.get(rand):
          return 'A draw!'

     elif opt_dict.get(rand) in options.get(user):
         return 'user won!'

     else
         return 'computer won!'
```

2. Penso que para solucionar esse requisito, seria um "if" simples do tipo de regra que quer seguir, o código seleciona a função check_bet ou check_options para fazer as verificações de acordo com as regras selecionadas.

**Comment by RodrigoBC2** [comment]
1. Eu pensei em fazer algo mais ou menos assim:

- Dicionário que armazena uma lista que tem por nome a opção selecionada e as posições são strings das opções que são derrotadas pela opção selecionada.

- Para verificar quem ganhou, criei uma função que tem como entrada as strings que ambos os competidores selecionaram e em seguida, 3 possíveis verificações: empate, se o usuário ganha ou se o computador ganha.

- Para evitar multiplas opções como na função check_bet, o elif faz uma simpels verificação se a string de input do computador está dentro da lista selecionada pelo usuário como "perdedora" da opção que ele escolheu. Se sim, usuário vence, se nao, computador vence.

```
options = { 0: scissors = ['PAPER', 'LIZARD'],
               1: paper = ['ROCK', 'SPOCK'],
               2: rock = ['SCISSORS', 'LIZARD'],
               3: lizard = ['PAPER', 'SPOCK'],
               4: spock = ['SCISSORS', 'ROCK'] }

def check_options(opt_dict.get(user), opt_dict.get(rand)):

     if opt_dict.get(user) == opt_dict.get(rand):
          return 'A draw!'

     elif opt_dict.get(rand) in options.get(user):
         return 'User won!'

     else
         return 'Computer won!'
```

2. Penso que para solucionar esse requisito, seria um "if" simples do tipo de regra que quer seguir, o código seleciona a função check_bet ou check_options para fazer as verificações de acordo com as regras selecionadas.

**Comment by drvpereira** [comment]
A ideia é exatamente essa!

**Comment by RodrigoBC2** [comment]
Criei uma nova Branch com o código atualizado, uma vez que é uma mudança radical. Se estiver ok, posso adicionar na main branch.
