### ISSUE TITLE
Feedback 2: variáveis desnecessárias e outros itens menores

### ISSUE THREAD

**Issue by drvpereira** [RodrigoBC2/rock-paper-scissors#5]
- As variáveis x e y das linhas 40 e 41 são desnecessárias. Você está apenas criando cópias de user e rand. Você pode fazer simplesmente conditionals(user, rand). 

- Uma dica de boa prática: o nome da função "conditionals" não tá muito legal. O nome da função deve ser, de preferência, algo que descreva o que ela está fazendo e, normalmente, tem um verbo envolvido. Uma sugestão: check_winner, ou algo assim.

- Perceba que, por causa do while da linha 57, a variável choice só pode ter dois valores: 'y' ou 'n'. Sendo assim, o elif da linha 66 é desnecessário, já que se não for 'y', vai ser 'n'. Então, na linha 66, você pode usar um else, em vez de um elif.

**Comment by RodrigoBC2** [comment]
1 - As variáveis foram alteradas como sugerid;
2 - o nome da função foi alterado para "check_bet";
3 - Acatada a sugestão de trocar o elif por else, por não ser mais necessário o elif.
