### ISSUE TITLE
Feature request: estatísticas

### ISSUE THREAD

**Issue by drvpereira** [RodrigoBC2/rock-paper-scissors#6]
Adicionar estatísticas após o fim do jogo:

- Quantos % de vezes o usuário ganhou?
- Quantos % de vezes o computador ganhou?
- Quantos % de vezes houve empate?
- Quantas vezes saiu pedra? Papel? Tesoura?
- O que mais você conseguir imaginar ai.

**Comment by RodrigoBC2** [comment]
Foram adicionados as estatísticas requeridas, porem na forma unitária. Em relação a quantas vezes saiu cada escolha, foi estratificado o número de vezes em que cada competidor escolheu uma opção, ao final do jogo.

**Comment by RodrigoBC2** [comment]
Adicionei a soma das vezes em que o computador e o usuario escolheram as opções, combinados.
