### ISSUE TITLE
Otimização no uso de variáveis

### ISSUE THREAD

**Issue by drvpereira** [RodrigoBC2/rock-paper-scissors#7]
Não é necessário fazer algo como:

        winner = 'A Draw!'
        return winner

Você pode simplesmente fazer:

        return 'A Draw!'

Com isso economiza variáveis e, consequentemente, a quantidade de memória alocada para o seu programa. Hoje em dia os compiladores/interpretadores são espertos o suficiente pra fazer esse tipo de otimização, mas é importante você saber porque existirão casos em que eles não farão.

**Comment by RodrigoBC2** [comment]
Concordo, alterei la no código.
