### ISSUE TITLE
Otimização do scoreboard

### ISSUE THREAD

**Issue by drvpereira** [RodrigoBC2/rock-paper-scissors#8]
A cada jogo, você adiciona três números a três listas:

        scoreboard['draw'].append(1)
        scoreboard['player'].append(0)
        scoreboard['computer'].append(0)

Mas no final das contas, você não precisa saber o que aconteceu em cada jogo, só precisa saber a soma total, tanto que faz um sum() pra exibir o resultado.

Que tal fazer:

scoreboard = {'draw': 0,
              'player': 0,
              'computer':0}

E a cada jogo:

        scoreboard['draw'] = scoreboard['draw'] + 1                   # ou scoreboard['draw'] += 1
        scoreboard['player'] = scoreboard['player'] + 1               # ou scoreboard['player'] += 1
        scoreboard['computer'] = scoreboard['computer'] + 1   # ou scoreboard['computer'] += 1

?

Pense que cada número desses ocupa 4 bytes em memória. Em 100 jogos, serão 100 x 3 (pq são 3 listas) x 4 bytes: 1200 bytes. Imagine agora que é um jogo online e tem 1 milhão de pessoas jogando: 1000000 x 3 x 4 =~ 12GB de memória. E você ainda tá fazendo essa mesma coisa com o options_counter, o que vai representar ainda mais consumo de memória. 

Mas se você usar simplesmente um número pra guardar a soma, independente do número de jogos sempre teremos apenas 3 x 4 bytes = 12 bytes.

Tente dar uma melhorada nessa questão.

**Comment by RodrigoBC2** [comment]
Quando eu estava fazendo, eu imaginei em utilizar apenas um número, porém a minha ideia seria deixar uma estrutura pronta para "salvar" uma sequencia de escolhas e/ou vitórias. Tipo um "kill streak". Faria sentido continuar utilizando essa estrutura?

**Comment by drvpereira** [comment]
Então, depende de como você for usar. Se for só um "kill streak", dá pra fazer da  seguinte forma:

```
if user_has_won:
     kill_streak['user'] += 1 # incrementa o kill streak do usuário
     kill_streak['computer'] = 0 # seta o kill streak do computador pra 0
elif computer_has_won:
     kill_streak['user'] = 0 # seta o kill streak do usuário pra 0
     kill_streak['computer'] += 1 # incrementa o kill streak do computador 
else:
     kill_streak['user'] = 0 # empate - ninguém ganhou, então zera os kill streaks
     kill_streak['computer'] = 0 
```

Dependendo do que você estiver pensando, pode fazer sentido guardar a lista, mas se você perceber que não vai usar, é melhor não ter.

**Comment by RodrigoBC2** [comment]
Ah, entendi, é uma boa solução mesmo. vou incrementar ao meu código.

**Comment by RodrigoBC2** [comment]
Incrementei no meu código levando em consideração as duas sugestões. No "kill_streak" que eu chamei de "win_streak" utilizei o seu código acima como um contador mesmo, ja que ele sempre é zerado quando a situação é alterada e adicionei um dicionario que armazena quantos "win_streak" cada player teve, tendo um threshold de 2 wins como base. Ao final do programa, adicionei a função de imprimir na tela a nova funcionalidade.
